version: 4.0.0-beta-build{build}
skip_non_tags: true
clone_depth: 1

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019
  - Ubuntu

environment:
  bit7z_version: 4.0.0-beta

  matrix:
  - compiler: msvc

  - compiler: msvc_mt
    flags: -DBIT7Z_STATIC_RUNTIME=ON

  - compiler: mingw
    generator: MinGW Makefiles
    
  - compiler: gcc
    generator: Unix Makefiles
    
  - compiler: clang
    generator: Unix Makefiles
    
platform:
  - x86
  - x64

matrix:
  fast_finish: true
  
  exclude:
    - image: Visual Studio 2015
      compiler: gcc
    - image: Visual Studio 2015
      compiler: clang
    - image: Visual Studio 2017
      compiler: mingw
    - image: Visual Studio 2017
      compiler: gcc
    - image: Visual Studio 2017
      compiler: clang
    - image: Visual Studio 2019
      compiler: mingw
    - image: Visual Studio 2019
      compiler: gcc
    - image: Visual Studio 2019
      compiler: clang
    - image: Ubuntu
      compiler: msvc
    - image: Ubuntu
      compiler: msvc_mt
    - image: Ubuntu
      compiler: mingw
      
init:
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator=Visual Studio 16 2019 )
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator=Visual Studio 15 2017 )
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" if NOT "%compiler%"=="mingw" ( set generator=Visual Studio 14 2015 )

before_build:
  - sh: arch=$platform
  - cmd: set arch=%platform% # preserving platform value (vcvarsall overwrites it)
  - cmd: if "%compiler:~0,4%"=="msvc" ( call %vcvarsall% %platform% )
  - cmd: if "%compiler:~0,5%"=="mingw" ( set PATH=%PATH%;C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\bin )
  - git submodule update --init --recursive
  - mkdir build
  - cd build

build_script:
  - cmake .. -G "%generator%" -DCMAKE_BUILD_TYPE=Release %flags%
  - cmake --build . -j
  - cmake .. -G "%generator%" -DCMAKE_BUILD_TYPE=Debug %flags%
  - cmake --build . -j

after_build:
  - cd ..
  # Windows images
  - cmd: if "%compiler%"=="mingw" ( 
            for /f %%i in ('g++ -dumpversion') do set tag=mingw%%i_%arch%
         ) else (
            set tag=%APPVEYOR_BUILD_WORKER_IMAGE:Visual Studio =msvc%%compiler:msvc=%_%arch%
         )
  - cmd: mkdir "pkg/bit7z/"
  - cmd: mkdir "pkg/bit7z/lib/"
  - cmd: mkdir "pkg/bit7z/include/"
  - cmd: copy lib\%arch%\*.* pkg\bit7z\lib\
  - cmd: copy include\bit*.hpp pkg\bit7z\include\
  - cmd: copy README.md pkg\bit7z\
  - cmd: copy LICENSE pkg\bit7z\
  # Ubuntu image
  - sh: [[ "$compiler" == "gcc" ]] && tag=g++$(g++ --version | grep ^g++ | sed 's/^.* //g')_$arch
  - sh: [[ "$compiler" == "clang" ]] && tag=g++$(clang --version | head -n 1 | sed -e 's/.* version \([0-9.]*\).*/\1/')_$arch
  - sh: mkdir -p pkg/bit7z/lib/
  - sh: mkdir -p pkg/bit7z/include/
  - sh: cp lib/$arch/*.* pkg/bit7z/lib/
  - sh: cp include/bit*.hpp pkg/bit7z/include/
  - sh: cp README.md pkg/bit7z/
  - sh: cp LICENSE pkg/bit7z/
  # Packaging
  - echo %bit7z_version% %tag% > "pkg/bit7z/BUILD.txt"
  - cd pkg
  - 7z a -t7z bit7z-v%bit7z_version%-%tag%.7z *

artifacts:
  - path: pkg/*.7z
    name: binary

test: off

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Binaries of Bit7z v%bit7z_version%'
  auth_token:
    secure: lBNuN4sQkluR2FDE6eGP811Dm2ooRkvDnxRL8YFPp0wMzaSEDoDtmOR04wZDL+LX
  artifact: /.*\.7z/
  draft: true
  prerelease: false
  on:
    # branch: master
    appveyor_repo_tag: true
