version: 4.0.0-beta-build{build}
skip_non_tags: true
clone_depth: 1

image:
  - Visual Studio 2015
  - Visual Studio 2017
  - Visual Studio 2019
  - Ubuntu

environment:
  bit7z_version: 4.0.0-beta

  matrix:
  - compiler: msvc
    generator: Ninja

  - compiler: msvc_mt
    generator: Ninja
    flags: -DBIT7Z_STATIC_RUNTIME=ON

  - compiler: mingw
    generator: MinGW Makefiles
    
  - compiler: gcc
    generator: Ninja
    
  - compiler: clang
    generator: Ninja
    
platform:
  - x86
  - x64

matrix:
  fast_finish: true
  
  exclude:
    - image: Visual Studio 2015
      compiler: gcc
    - image: Visual Studio 2015
      compiler: clang
    - image: Visual Studio 2017
      compiler: gcc
    - image: Visual Studio 2017
      compiler: clang
    - image: Visual Studio 2019
      compiler: gcc
    - image: Visual Studio 2019
      compiler: clang
    - image: Ubuntu
      compiler: msvc
    - image: Ubuntu
      compiler: msvc_mt
    - image: Ubuntu
      compiler: mingw

before_build:
  - git submodule update --init --recursive

build_script:
  - cmake . -G "%generator%" -DCMAKE_BUILD_TYPE=Release %flags%
  - cmake --build . -j
  - cmake . -G "%generator%" -DCMAKE_BUILD_TYPE=Debug %flags%
  - cmake --build . -j

after_build:
  - cmd: set tag=%APPVEYOR_BUILD_WORKER_IMAGE:Visual Studio =msvc%%compiler:msvc=%_%platform%
  - cmd: mkdir "pkg/bit7z/"
  - cmd: mkdir "pkg/bit7z/lib/"
  - cmd: mkdir "pkg/bit7z/include/"
  - cmd: copy lib\%platform%\*.* pkg\bit7z\lib\
  - cmd: copy include\bit*.hpp pkg\bit7z\include\
  - cmd: copy README.md pkg\bit7z\
  - cmd: copy LICENSE pkg\bit7z\
  - sh: set tag=g++$(g++ --version | grep ^g++ | sed 's/^.* //g')_%platform%
  - sh: mkdir -p pkg/bit7z/lib/
  - sh: mkdir -p pkg/bit7z/include/
  - sh: cp lib/%platform%/*.* pkg/bit7z/lib/
  - sh: cp include/bit*.hpp pkg/bit7z/include/
  - sh: cp README.md pkg/bit7z/
  - sh: cp LICENSE pkg/bit7z/
  - echo %bit7z_version% %tag% > "pkg/bit7z/BUILD.txt"
  - cd pkg
  - 7z a -t7z bit7z-v%bit7z_version%-%tag%.7z *

artifacts:
  - path: pkg/*.7z
    name: binary

test: off

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Binaries of Bit7z v%bit7z_version%'
  auth_token:
    secure: /WV4rvJOHuV7V0UVzX96DF61dznIJdluPBPIVDGKiQDz3EPQ0ETnyIJ8bDTLHUXT
  artifact: /.*\.7z/
  draft: true
  prerelease: false
  on:
    # branch: master
    appveyor_repo_tag: true
