blank_issues_enabled: true
contact_links:
  - name: Report a bug, propose new features, and receive help
    url: https://github.com/rikyoz/bit7z/issues
    about: This is the issue tracker of bit7z. Please ask and answer questions here.
